package com.huah.ai.platform.agent.tools;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Slf4j
@Component
public class CodeTools {

    private static final TypeReference<Map<String, Object>> MAP_TYPE = new TypeReference<>() {
    };

    private final ChatModel chatModel;
    private final ObjectMapper objectMapper;

    public CodeTools(ChatModel chatModel, ObjectMapper objectMapper) {
        this.chatModel = chatModel;
        this.objectMapper = objectMapper;
    }

    @Tool(description = "Analyze a code snippet and predict its execution result without executing it.")
    public Map<String, Object> executeCode(
            @ToolParam(description = "Programming language: java|python|javascript|go") String language,
            @ToolParam(description = "Code to analyze") String code) {
        log.info("[Tool] executeCode (AI analysis): language={}, codeLength={}", language, code.length());
        try {
            String prompt = String.format("""
                    Analyze the following %s code and predict its execution result.
                    Requirements:
                    1. Return the expected standard output (stdout)
                    2. Return the possible standard error output (stderr)
                    3. Predict the exit code (0 for success, non-zero for failure)
                    4. Provide a short explanation of the code flow

                    Output strictly in the following format, one field per line:
                    STDOUT: <expected stdout>
                    STDERR: <expected stderr, or blank>
                    EXIT_CODE: <exit code>
                    ANALYSIS: <short explanation>

                    Code:
                    ```%s
                    %s
                    ```
                    """, language, language, code);

            String aiResponse = chatModel.call(prompt);
            String stdout = extractField(aiResponse, "STDOUT");
            String stderr = extractField(aiResponse, "STDERR");
            String exitCodeStr = extractField(aiResponse, "EXIT_CODE");
            String analysis = extractField(aiResponse, "ANALYSIS");

            int exitCode;
            try {
                exitCode = Integer.parseInt(exitCodeStr.trim());
            } catch (NumberFormatException e) {
                exitCode = 0;
            }

            Map<String, Object> result = new HashMap<>();
            result.put("language", language);
            result.put("stdout", stdout);
            result.put("stderr", stderr);
            result.put("exitCode", exitCode);
            result.put("analysis", analysis);
            result.put("note", "Result is generated by AI analysis and was not actually executed");
            return result;
        } catch (Exception e) {
            log.error("[Tool] executeCode analysis failed: {}", e.getMessage(), e);
            return ToolResponseSupport.error("Code analysis failed: " + e.getMessage(), "CODE_ANALYSIS_FAILED");
        }
    }

    @Tool(description = "Search code in a Git repository. This is currently a placeholder until a real provider is configured.")
    public List<Map<String, String>> searchGitRepo(
            @ToolParam(description = "Repository name or URL") String repo,
            @ToolParam(description = "Search keyword or regular expression") String query) {
        log.info("[Tool] searchGitRepo (not yet enabled): repo={}, query={}", repo, query);
        return List.of(Map.of(
                "info", "Git repository search is not enabled yet. Configure a provider token before turning it on.",
                "repo", repo,
                "query", query
        ));
    }

    @Tool(description = "Review code for correctness, style, performance, and security issues.")
    public Map<String, Object> reviewCode(
            @ToolParam(description = "Programming language") String language,
            @ToolParam(description = "Code to review") String code) {
        log.info("[Tool] reviewCode: language={}, codeLength={}", language, code.length());
        try {
            String prompt = String.format("""
                    You are a senior code reviewer. Review the following %s code.
                    Cover these areas:
                    1. Security issues
                    2. Code style and readability
                    3. Performance problems
                    4. Logic and boundary-condition bugs
                    5. Best-practice suggestions

                    Return valid JSON only in this shape:
                    {
                      "issues": [
                        {
                          "severity": "HIGH|MEDIUM|LOW",
                          "type": "security|style|performance|logic",
                          "message": "Issue description",
                          "line": 1,
                          "suggestion": "Fix suggestion"
                        }
                      ],
                      "score": "X/10",
                      "summary": "Overall review summary"
                    }

                    Code:
                    ```%s
                    %s
                    ```
                    """, language, language, code);

            String aiResponse = chatModel.call(prompt);
            try {
                String json = extractJson(aiResponse);
                return objectMapper.readValue(json, MAP_TYPE);
            } catch (Exception parseEx) {
                log.warn("[Tool] reviewCode: AI response is not valid JSON, returning raw text");
                Map<String, Object> result = new HashMap<>();
                result.put("rawReview", aiResponse);
                result.put("note", "AI returned an unstructured review payload");
                return result;
            }
        } catch (Exception e) {
            log.error("[Tool] reviewCode failed: {}", e.getMessage(), e);
            return ToolResponseSupport.error("Code review failed: " + e.getMessage(), "CODE_REVIEW_FAILED");
        }
    }

    private String extractField(String text, String fieldName) {
        String prefix = fieldName + ":";
        int start = text.indexOf(prefix);
        if (start < 0) {
            return "";
        }
        start += prefix.length();
        int end = text.indexOf("\n", start);
        if (end < 0) {
            end = text.length();
        }
        return text.substring(start, end).trim();
    }

    private String extractJson(String text) {
        String json = text.trim();
        if (json.contains("```json")) {
            json = json.substring(json.indexOf("```json") + 7);
            json = json.substring(0, json.indexOf("```"));
        } else if (json.contains("```")) {
            json = json.substring(json.indexOf("```") + 3);
            if (json.startsWith("\n")) {
                json = json.substring(1);
            }
            json = json.substring(0, json.indexOf("```"));
        }
        return json.trim();
    }
}
